version: '3'
services:
  cf-test-sonarqube:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_SERVICE_NAME}
    env_file: .env
    command: "functions-framework --target=init --debug"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./reports:/app/reports
    ports:
      - "${DOCKER_PORT}:8080"
    networks:
      - backend
networks:
  backend:
    external:
      name: ${DOCKER_NETWORK}